"""
Django settings for pilates_cobranca project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hgssxmukn$2ufn22780*v%4i(191mnw3v678urje%ndm#+d1g9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']  # Para desenvolvimento. Em produção, especifique os hosts permitidos


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',          # CORS para integração com React
    'cobranca_app',         # Aplicativo principal
    'rest_framework',       # API REST
    'django_apscheduler',   # Agendador de tarefas
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (deve estar antes de CommonMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pilates_cobranca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pilates_cobranca.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

META_API_SETTINGS = {
    'TOKEN': 'EAAcXBNICQXABP6H8blOyf97ldoujQfEHErSR6rQpAGutQbsuC3oJqYSOwITlREv2uZC1fpX0T0nCB399wu4QZAH0dzQfmmaZCM6ZA2yUo071rwdypzhXpsknZAc3rjFKCXDdz1EJkzJGQgcjwJEp3rO1ZBT0kZAJNQ5dSCYybA1QgmgCseD9RQEjVgbvneJ8JAWTI8DG3ZBuv0LssYScxtNUF6MFaDdr3vdKhYZAZCtzhIH9n2t8cQpGZC7Nf23bB9pBgnmdURP4ljZAWJZBchLnPVQ2o', # SEU TOKEN REAL
    'PHONE_ID': '887155537805840', # SEU PHONE ID REAL
    'URL_BASE': 'https://graph.facebook.com/v22.0/', # A versão da API que está no seu cURL
    'MOCK_MODE': False, # MODO DE PRODUÇÃO REAL!
    'WHATSAPP_ENABLED': False, # Kill Switch: Define como False para desativar envio de WhatsApp sem afetar E-mail
}
# =================================================================
# CONFIGURAÇÃO DE E-MAIL (LINHA 16)
# Usando o Gmail como SMTP de Exemplo
# =================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # Servidor SMTP do Gmail
EMAIL_PORT = 587             # Porta TLS
EMAIL_USE_TLS = True         # Usa protocolo de segurança TLS
EMAIL_HOST_USER = 'nayanda.robers@gmail.com' # SEU ENDEREÇO DE EMAIL GMAIL
EMAIL_HOST_PASSWORD = 'turimfzxteukzrvf' # SENHA DE APP
DEFAULT_FROM_EMAIL = 'nayanda.robers@gmail.com'

# =================================================================
# CONFIGURAÇÃO CORS PARA INTEGRAÇÃO COM REACT
# =================================================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev server padrão
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# =================================================================
# CONFIGURAÇÃO REST FRAMEWORK
# =================================================================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Para desenvolvimento. Em produção, usar autenticação
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'EXCEPTION_HANDLER': 'cobranca_app.core.exception_handler.excecao_handler_customizado',
}