"""
Django settings for pilates_cobranca project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hgssxmukn$2ufn22780*v%4i(191mnw3v678urje%ndm#+d1g9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cobranca_app',  # <-- NOVO: Nosso aplicativo principal
    'rest_framework',      # <-- Para criar a API REST
    'django_apscheduler',  # <-- Nosso agendador simplificado
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pilates_cobranca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pilates_cobranca.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

META_API_SETTINGS = {
    'TOKEN': 'EAAcXBNICQXABP6H8blOyf97ldoujQfEHErSR6rQpAGutQbsuC3oJqYSOwITlREv2uZC1fpX0T0nCB399wu4QZAH0dzQfmmaZCM6ZA2yUo071rwdypzhXpsknZAc3rjFKCXDdz1EJkzJGQgcjwJEp3rO1ZBT0kZAJNQ5dSCYybA1QgmgCseD9RQEjVgbvneJ8JAWTI8DG3ZBuv0LssYScxtNUF6MFaDdr3vdKhYZAZCtzhIH9n2t8cQpGZC7Nf23bB9pBgnmdURP4ljZAWJZBchLnPVQ2o', # SEU TOKEN REAL
    'PHONE_ID': '887155537805840', # SEU PHONE ID REAL
    'URL_BASE': 'https://graph.facebook.com/v22.0/', # A versão da API que está no seu cURL
    'MOCK_MODE': False, # MODO DE PRODUÇÃO REAL!
}
# =================================================================
# CONFIGURAÇÃO DE E-MAIL (LINHA 16)
# Usando o Gmail como SMTP de Exemplo
# =================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # Servidor SMTP do Gmail
EMAIL_PORT = 587             # Porta TLS
EMAIL_USE_TLS = True         # Usa protocolo de segurança TLS
EMAIL_HOST_USER = 'nayanda.robers@gmail.com' # SEU ENDEREÇO DE EMAIL GMAIL
EMAIL_HOST_PASSWORD = 'turimfzxteukzrvf' # SENHA DE APP
DEFAULT_FROM_EMAIL = 'nayanda.robers@gmail.com'