# Generated by Django 5.2.7 on 2025-10-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=100)),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidade_meses', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano de Serviço',
                'verbose_name_plural': 'Planos de Serviço',
            },
        ),
    ]
