# Generated by Django 5.2.7 on 2025-10-30 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone_whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('data_inicio_contrato', models.DateField()),
                ('status_cliente', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO_ATRASO', 'Inativo por Atraso'), ('INATIVO_MANUAL', 'Inativo Manual')], default='ATIVO', max_length=20)),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cobranca_app.plano')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_multa_juros', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total_devido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('referencia_ciclo', models.CharField(max_length=7)),
                ('status_cobranca', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranca_app.cliente')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regua', models.CharField(max_length=50)),
                ('tipo_canal', models.CharField(max_length=10)),
                ('conteudo_mensagem', models.TextField()),
                ('data_agendada', models.DateTimeField()),
                ('data_envio_real', models.DateTimeField(blank=True, null=True)),
                ('status_envio', models.CharField(choices=[('AGENDADO', 'Agendado'), ('ENVIADO', 'Enviado'), ('FALHA', 'Falha')], default='AGENDADO', max_length=10)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranca_app.cobranca')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_agendada'],
            },
        ),
    ]
