# Generated by Django 5.2.7 on 2025-11-19 20:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca_app', '0003_preparar_cpf_como_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ['nome_plano'], 'verbose_name': 'Plano de Serviço', 'verbose_name_plural': 'Planos de Serviço'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(help_text='CPF do cliente (apenas números, 11 dígitos)', max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_inicio_contrato',
            field=models.DateField(verbose_name='Data de Início do Contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(help_text='E-mail único do cliente', max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cobranca_app.plano', verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status_cliente',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO_ATRASO', 'Inativo por Atraso'), ('INATIVO_MANUAL', 'Inativo Manual')], default='ATIVO', max_length=20, verbose_name='Status do Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_whatsapp',
            field=models.CharField(help_text='Telefone no formato: código do país + DDD + número', max_length=20, unique=True, verbose_name='Telefone WhatsApp'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranca_app.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='referencia_ciclo',
            field=models.CharField(max_length=7, verbose_name='Referência do Ciclo'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='status_cobranca',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status da Cobrança'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='valor_multa_juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Multa e Juros'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='valor_total_devido',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total Devido'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='cobranca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranca_app.cobranca', verbose_name='Cobrança'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='conteudo_mensagem',
            field=models.TextField(verbose_name='Conteúdo da Mensagem'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_agendada',
            field=models.DateTimeField(verbose_name='Data Agendada'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_envio_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio Real'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='status_envio',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('ENVIADO', 'Enviado'), ('FALHA', 'Falha')], default='AGENDADO', max_length=10, verbose_name='Status de Envio'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo_canal',
            field=models.CharField(max_length=10, verbose_name='Tipo de Canal'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo_regua',
            field=models.CharField(max_length=50, verbose_name='Tipo de Régua'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome_plano',
            field=models.CharField(max_length=100, verbose_name='Nome do Plano'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='periodicidade_meses',
            field=models.IntegerField(default=1, verbose_name='Periodicidade (meses)'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base'),
        ),
    ]
