# Generated by Django 5.2.7 on 2025-12-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca_app', '0004_alter_cliente_options_alter_plano_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(help_text='CPF do cliente (pode incluir pontos e traço)', max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='CPF'),
        ),
    ]
